# SPDX-FileCopyrightText: 2024 GreaseMonk
# SPDX-FileCopyrightText: 2024 Qulibly
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2025 Blu
# SPDX-FileCopyrightText: 2025 Checkraze
# SPDX-FileCopyrightText: 2025 Dvir
# SPDX-FileCopyrightText: 2025 LukeZurg22
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 Whatstone
# SPDX-FileCopyrightText: 2025 dustylens
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: sectorService
  id: PirateBounties
  components:
  - type: SectorPirateBountyDatabase

- type: sectorService
  id: Mail
  components:
  - type: SectorLogisticStats
  - type: SectorMail # Contains sector-wide mail parameters

- type: sectorService
  id: ShuttleRecords
  components:
  - type: SectorShuttleRecords

# mono edit
- type: sectorService
  id: BankAccounts
  components:
  - type: SectorBank
    accounts:
      Frontier:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 14 # ~50K per hour, minimum wage employees!
      Nfsd:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 65 # ~234K per hour, about enough for minimum wage for the default TSFMC size
      Medical:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 18 # ~65K per hour, a bit over for the DOC MOM's wage.
      BlackMarket:
        !type:SectorBankAccountInfo
        balance: 0
        increasePerSecond: 1 # black market scam zone, not originally intended to be used properly - Note, don't set to 0, it'll cause annoying spam info messages
# mono edit end

 # A global source of character records (DNA, fingerprints, criminal records, etc.)
- type: sectorService
  id: SectorRecords
  components:
  - type: StationRecords

- type: sectorService
  id: Alerts
  components:
  - type: AlertLevel
    alertLevelPrototype: stationAlerts

- type: sectorService
  id: BountyContracts
  components:
  - type: BountyContractData
