# SPDX-FileCopyrightText: 2024 Checkraze
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 Daniel Lenrd
# SPDX-FileCopyrightText: 2025 core-mene
# SPDX-FileCopyrightText: 2025 mikusssssss
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 28800 # mono - change to 8hrs
  icon: "JobIconPilot"
  supervisors: job-supervisors-hire
  weight: 2 # Prioritize station & department jobs
  displayWeight: 30 # Second from the top
  accessGroups: # Frontier
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: SurgerySpeedModifier
        SpeedModifier: 1.25
