# SPDX-FileCopyrightText: 2023 Banshee
# SPDX-FileCopyrightText: 2023 Cheackraze
# SPDX-FileCopyrightText: 2023 Kesiath
# SPDX-FileCopyrightText: 2023 PECK
# SPDX-FileCopyrightText: 2023 checkraze
# SPDX-FileCopyrightText: 2024 Checkraze
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 ErhardSteinhauer
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 ark1368
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-description-mail-carrier # Mono
  startingGear: MailCarrierGear
  alwaysUseSpawner: true
  playTimeTracker: JobMailCarrier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  icon: "JobIconMailCarrier"
  supervisors: job-supervisors-sr
  weight: 90 # Frontier
  displayWeight: 30 # Frontier
  canBeAntag: false
  access:
  - External # Frontier
  - Maintenance
  - Service
  - Mail # Frontier
  - Frontier # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial # Frontier
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: MailCarrierGear
  equipment:
    head: ClothingHeadMailCarrier
    eyes: ClothingEyesHudMail
    id: CourierPDA
#    ears: ClothingHeadsetService # Frontier - ClothingHeadsetCargo<ClothingHeadsetService
    belt: MailBag
  storage:
    back:
    - EncryptionKeyService # Frontier
    - HandheldCrewMonitor # Frontier
    - ShipVoucherFrontierMailCarrier # Frontier
    - MailMetricsCartridge # Frontier
