# SPDX-FileCopyrightText: 2023 LankLTE
# SPDX-FileCopyrightText: 2023 Leon Friedrich
# SPDX-FileCopyrightText: 2024 Jezithyr
# SPDX-FileCopyrightText: 2025 Ark
# SPDX-FileCopyrightText: 2025 Redrover1760
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Shitmed Change: this entire file is reorganized for shitmed:
# Instead of random species parts inheriting BaseItem and copy pasting stuff,
# EVERYTHING inherits either BasePart or BasePartInorganic.
# Then individual part LS just inherits from PartSBase and BaseL where S and L are the species and limb.
# All limbs have the usual state, PartSBase just needs to set the rsi for sprite and icon
- type: entity
  abstract: true
  parent: BaseItem
  id: BasePartInorganic
  name: "body part"
  components:
  - type: Icon
    sprite: Mobs/Species/Human/parts.rsi
  - type: Damageable
    damageContainer: Inorganic # Shitmed Change
  - type: BodyPart
  - type: SurgeryTool # Shitmed Change
    startSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ1.ogg
    endSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ2.ogg
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
    - Trash

- type: entity
  abstract: true
  id: BaseTorsoInorganic
  name: "torso"
  components:
  - type: Sprite
    state: "torso_m"
  - type: Icon
    state: "torso_m"
  - type: BodyPart
    partType: Torso
    # Shitmed Change Start
    toolName: "a torso"
    containerName: "torso_slot"
    children:
      right arm:
        id: right arm
        type: Arm
      left arm:
        id: left arm
        type: Arm
      right leg:
        id: right leg
        type: Leg
      left leg:
        id: left leg
        type: Leg
      head:
        id: head
        type: Head
    organs:
      heart:
        id: heart
      lungs:
        id: lungs
      stomach:
        id: stomach
      liver:
        id: liver
      kidneys:
        id: kidneys
  - type: ContainerContainer
    containers:
      torso_slot: !type:ContainerSlot {}
    # Shitmed Change End

- type: entity
  abstract: true
  id: BaseHead
  name: "head"
  components:
  - type: Sprite
    state: "head_m"
  - type: Icon
    state: "head_m"
  - type: BodyPart
    partType: Head
    toolName: "a head" # Shitmed Change
    vital: true
    severIntegrity: 400 # Mono
    organs: # Shitmed Change
      brain:
        id: brain
      eyes:
        id: eyes
  - type: Input
    context: "ghost"
  - type: Tag
    tags:
      - Head
  - type: Destructible # Mono
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 500 # 110->500
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 600 # 150->600
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 700 # 200->700
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact

- type: entity
  abstract: true
  parent: MajorLimb # Mono
  id: BaseLeftArm
  name: "left arm"
  components:
  - type: Sprite
    state: "l_arm"
  - type: Icon
    state: "l_arm"
  - type: BodyPart
    partType: Arm
    symmetry: Left
    toolName: "a left arm" # Shitmed Change
    children: # Shitmed Change
      left hand:
        id: left hand
        type: Hand

- type: entity
  abstract: true
  parent: MajorLimb # Mono
  id: BaseRightArm
  name: "right arm"
  components:
  - type: Sprite
    state: "r_arm"
  - type: Icon
    state: "r_arm"
  - type: BodyPart
    partType: Arm
    symmetry: Right
    toolName: "a right arm" # Shitmed Change
    children: # Shitmed Change
      right hand:
        id: right hand
        type: Hand
    severIntegrity: 160 # Mono

- type: entity
  abstract: true
  parent: MinorLimb # Mono
  id: BaseLeftHand
  name: "left hand"
  components:
  - type: Sprite
    state: "l_hand"
  - type: Icon
    state: "l_hand"
  - type: BodyPart
    partType: Hand
    symmetry: Left
    toolName: "a left hand" # Shitmed Change

- type: entity
  abstract: true
  parent: MinorLimb # Mono
  id: BaseRightHand
  name: "right hand"
  components:
  - type: Sprite
    state: "r_hand"
  - type: Icon
    state: "r_hand"
  - type: BodyPart
    partType: Hand
    symmetry: Right
    toolName: "a right hand" # Shitmed Change

- type: entity
  abstract: true
  parent: MajorLimb # Mono
  id: BaseLeftLeg
  name: "left leg"
  components:
  - type: Sprite
    state: "l_leg"
  - type: Icon
    state: "l_leg"
  - type: BodyPart
    partType: Leg
    symmetry: Left
    toolName: "a left leg" # Shitmed Change
    children: # Shitmed Change
      left foot:
        id: left foot
        type: Foot
  - type: MovementBodyPart

- type: entity
  abstract: true
  parent: MajorLimb # Mono
  id: BaseRightLeg
  name: "right leg"
  components:
  - type: Sprite
    state: "r_leg"
  - type: Icon
    state: "r_leg"
  - type: BodyPart
    partType: Leg
    symmetry: Right
    toolName: "a right leg" # Shitmed Change
    children: # Shitmed Change
      right foot:
        id: right foot
        type: Foot
  - type: MovementBodyPart

- type: entity
  abstract: true
  parent: MinorLimb # Mono
  id: BaseLeftFoot
  name: "left foot"
  components:
  - type: Sprite
    state: "l_foot"
  - type: Icon
    state: "l_foot"
  - type: BodyPart
    partType: Foot
    symmetry: Left
    toolName: "a left foot" # Shitmed Change

- type: entity
  abstract: true
  parent: MinorLimb # Mono
  id: BaseRightFoot
  name: "right foot"
  components:
  - type: Sprite
    state: "r_foot"
  - type: Icon
    state: "r_foot"
  - type: BodyPart
    partType: Foot
    symmetry: Right
    toolName: "a right foot" # Shitmed Change

- type: entity # Mono
  abstract: true
  id: MajorLimb
  components:
  - type: BodyPart
    severIntegrity: 160
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 190 # 110->190
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 210 # 150->210
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 250 # 200->250
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact


- type: entity # Mono
  abstract: true
  id: MinorLimb
  components:
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 150 # 110->150
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 180 # 150->180
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 230 # 200->230
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
