# SPDX-FileCopyrightText: 2024 AndresE55
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: ThrusterSecurity
  parent: Thruster # Mono - Removed BaseStructureDisableAnchoring
  name: thruster
  suffix: Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/thrustersecurity.rsi
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1500  # Considering we need a lot of thrusters didn't want to make an individual one too tanky
      behaviors:
        - !type:DoActsBehavior
          acts: ["Destruction"]
  - type: Machine
    board: ThrusterSecurityMachineCircuitboard

- type: entity
  id: DebugThrusterSecurity
  parent: DebugThruster # Mono - Removed BaseStructureDisableAnchoring
  name: thruster
  suffix: DEBUG, Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/thrustersecurity.rsi
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1500  # Considering we need a lot of thrusters didn't want to make an individual one too tanky
      behaviors:
        - !type:DoActsBehavior
          acts: ["Destruction"]
  - type: Machine
    board: ThrusterSecurityMachineCircuitboard
  - type: ContainerContainer
    containers:
      machine_board: !type:Container # FIXME: Why do these need to be defined here?  What's missing?
      machine_parts: !type:Container

- type: entity
  id: GyroscopeSecurity
  parent: Gyroscope # Mono - Removed BaseStructureDisableAnchoring
  suffix: Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/gyroscope.rsi
  - type: Machine
    board: GyroscopeSecurityMachineCircuitboard

- type: entity
  id: DebugGyroscopeSecurity
  parent: DebugGyroscope # Mono - Removed BaseStructureDisableAnchoring
  name: gyroscope
  suffix: DEBUG, Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/gyroscope.rsi
  - type: Machine
    board: GyroscopeSecurityMachineCircuitboard
  - type: ContainerContainer
    containers:
      machine_board: !type:Container # FIXME: Why do these need to be defined here?  What's missing?
      machine_parts: !type:Container

- type: entity
  id: SmallGyroscopeSecurity
  parent: GyroscopeSecurity
  name: small gyroscope
  suffix: Security
  components:
  - type: Thruster
    baseThrust: 250
    thrust: 250
  - type: ApcPowerReceiver
    powerLoad: 200
  - type: Sprite
    scale: 0.8, 0.8
    sprite: _NF/Structures/Shuttles/gyroscope.rsi
  - type: StaticPrice
    price: 100
  - type: Machine
    board: SmallGyroscopeSecurityMachineCircuitboard
